version: "3.3"
services:

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: star-planet
      POSTGRES_USER: star
      POSTGRES_PASSWORD: planet
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
